export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const CLEAN_ERRORS = 'CLEAN_ERRORS'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const RENEW_SUCCESS = 'RENEW_SUCCESS'
export const RENEW_FAILED = 'RENEW_FAILED'