export const SET_USERS = 'SET_USERS' 
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT' 
export const NEW_MESSAGE = 'NEW_MESSAGE' 
export const SET_MESSAGES = 'SET_MESSAGES' 
export const LOGOUT = 'LOGOUT' 
